"""
File:           scanner.py

Last Updated:   Sept 9th 2025

Description:    all funtionality needed to scan and parse
                input strings in the form of a file or using 
                the built in shell

Author:         Blake Collins
"""

# imports
from custom_token import *


class Scanner:
    """
    A simple scanner (lexer) that reads a source string and
    converts it into a sequence of tokens.
    
    Attributes:
        source (str): The input string to scan.
        current (int): Current position in the source.
        tokens (list): List of tokens generated by scanning.
    """

    keywords = {
        "new": TokenValue.NEW,
        "true": TokenValue.TRUE,
        "false": TokenValue.FALSE,
        "sloth": TokenValue.SLOTH,
        "null": TokenValue.NULL,
        "and": TokenValue.AND,
        "or": TokenValue.OR,
        "if": TokenValue.IF,
        "else": TokenValue.ELSE,
        "while": TokenValue.WHILE,
        "for": TokenValue.FOR,
        "print": TokenValue.PRINT,
        "give": TokenValue.GIVE,
        "super": TokenValue.SUPER,
        "this": TokenValue.THIS,
        "fun": TokenValue.FUN,
    }
    
    def __init__(self, source):
        """
        Initialize the Scanner with a source string.

        Args:
            source (str): The input string to scan.
        """
        self.source = source
        self.current = 0
        self.tokens = []
        self.line = 1


    def scan_tokens(self):
        """
        Scan the entire source string and return a list of tokens.
        
        Returns:
            list: A list of Token objects representing the source.
        """
        while not self.eof_reached():
            self.start = self.current
            self.scan_token()

        self.tokens.append(Token(TokenValue.EOF, "", None, self.line))
        return self.tokens
    

    def add_token(self, type, literal=None):
        """
        Add a token to the token list.

        Args:
            type (TokenValue): The type of token to add.
            literal (optional): The literal value associated with the token.
        """
        text = self.source[self.start:self.current]
        self.tokens.append(Token(type, text, literal, self.line))
    

    def scan_token(self):
        """
        Scan a single character and generate a token if recognized.
        """
        char = self.advance()

        if char == "(":
            self.add_token(TokenValue.LEFT_PAREN)

        elif char == ")":
            self.add_token(TokenValue.RIGHT_PAREN)
        
        elif char == "{":
            self.add_token(TokenValue.LEFT_BRACE)
        
        elif char == "}":
            self.add_token(TokenValue.RIGHT_BRACE)
        
        elif char == "[":
            self.add_token(TokenValue.LEFT_BRACKET)
        
        elif char == "]":
            self.add_token(TokenValue.RIGHT_BRACKET)
        
        elif char == ",":
            self.add_token(TokenValue.COMMA)
        
        elif char == ".":
            self.add_token(TokenValue.DOT)
        
        elif char == ";":
            self.add_token(TokenValue.SEMICOLON)
        
        elif char == "*":
            self.add_token(TokenValue.STAR)
        
        elif char == "+":
            if self.match("+"):
                self.add_token(TokenValue.PLUSPLUS)
            else:
                self.add_token(TokenValue.PLUS)
        
        elif char == "-":
            if self.match("-"):
                self.add_token(TokenValue.MINUSMINUS)
            else:
                self.add_token(TokenValue.MINUS)
        
        elif char == "/":
            # Handle comments
            if self.match("/"):
                while self.peek(1) != "\n" and not self.eof_reached():
                    self.advance()
            else:
                self.add_token(TokenValue.SLASH)
        
        elif char == "=":
            if self.match("="):
                self.add_token(TokenValue.EQUAL_EQUAL)
            else:
                self.add_token(TokenValue.EQUAL)
        
        elif char == "!":
            if self.match("="):
                self.add_token(TokenValue.BANG_EQUAL)
            else:
                self.add_token(TokenValue.BANG)
        
        elif char == ">":
            if self.match("="):
                self.add_token(TokenValue.GREATER_EQUAL)
            else:
                self.add_token(TokenValue.GREATER)
        
        elif char == "<":
            if self.match("="):
                self.add_token(TokenValue.LESS_EQUAL)
            else:
                self.add_token(TokenValue.LESS)
        
        elif char == '"':
            while self.peek(1) != '"' and not self.eof_reached():
                if self.peek(1) == "\n":
                    self.line += 1
                self.advance()

            if self.eof_reached():
                raise Exception("Unterminated string literal")

            # Closing "
            self.advance()
            value = self.source[self.start + 1:self.current - 1]
            self.add_token(TokenValue.STRING, value)
        
        elif char.isdigit():
            while self.peek(1).isdigit():
                self.advance()

            # Decimal part
            if self.peek(1) == "." and self.peek(2)[1].isdigit():
                self.advance()  # consume '.'
                while self.peek(1).isdigit():
                    self.advance()

            value = self.source[self.start:self.current]
            self.add_token(TokenValue.NUMBER, float(value) if "." in value else int(value))
        
        # Handle identifiers and keywords.
        elif char.isalpha() or char == "_":
            while self.peek(1).isalnum() or self.peek(1) == "_":
                self.advance()

            text = self.source[self.start:self.current]
            token_type = self.keywords.get(text, TokenValue.IDENTIFIER)
            self.add_token(token_type)
        
        elif char in [" ", "\r", "\t"]:
            pass  # Ignore whitespace
        
        elif char == "\n":
            self.line += 1

        else:
            raise Exception(f"ERROR: UNEXPECTED CHARACTER '{char}' AT LINE {self.line}")


    def match(self, expected):
        """Check if the next character matches the expected one."""
        if self.eof_reached():
            return False
        if self.source[self.current] != expected:
            return False
        self.current += 1
        return True
    

    def peek(self, n: int):
        """
        Peek at the next n characters without consuming them

        Args:
            n (int):    The ammount of characters you want
                        to look ahead.

        Returns:
            char: The next nth characters in the source
        """
        if self.current + n - 1 >= len(self.source):
            return "\0"
        return self.source[self.current:self.current + n]


    def advance(self):
        """
        Consume the next character from the source.

        Returns:
            char: The consumed character.
        """
        self.current += 1
        return self.source[self.current-1]
    

    def eof_reached(self):
        """
        Check if the end of the source has been reached.

        Returns:
            bool: True if all characters have been consumed, False otherwise.
        """
        return self.current >= len(self.source)