import os

def define_ast(output_dir, base_name, types):
    """
    Generates <base_name.lower()>.py in output_dir containing:
      - base class <base_name>
      - subclasses for each type in `types`
    `types` is a list of strings like "Binary : left, operator, right"
    """
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, f"{base_name.lower()}.py")
    with open(path, "w") as f:
        # Header
        f.write("# This file was generated by ast_generator.py\n\n")
        f.write(f"class {base_name}:\n")
        f.write("    \"\"\"Base class for AST nodes.\"\"\"\n")
        f.write("    pass\n\n\n")

        # Each node class
        for type_def in types:
            class_name, fields = [part.strip() for part in type_def.split(":")]
            field_list = [f.strip() for f in fields.split(",")] if fields else []
            f.write(define_type(base_name, class_name, field_list))
            f.write("\n")

def define_type(base_name, class_name, fields):
    """Return the class source code string for `class_name`."""
    r = f"class {class_name}({base_name}):\n"

    # __init__
    args = ", ".join(fields)
    r += f"    def __init__(self, {args}):\n" if args else "    def __init__(self):\n"
    if not fields:
        r += "        pass\n"
    else:
        for field in fields:
            r += f"        self.{field} = {field}\n"

    r += "\n"
    return r

if __name__ == "__main__":
    # Example usage
    types = [
        "Binary     : left, operator, right",
        "Grouping   : expression",
        "Literal    : value",
        "Unary      : operator, right"
    ]
    define_ast(".", "Expression", types)
    print("Wrote ./expression.py")
