import os

def define_ast(output_dir, base_name, types):
    """
    Generates <base_name.lower()>.py in output_dir containing:
      - base class <base_name>
      - subclasses for each type in `types`
    `types` is a list of strings like "Binary : left, operator, right"
    """
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, f"{base_name.lower()}.py")
    
    # Write Header to file
    with open(path, "w") as f:
        f.write("# AUTO GENERATED BY: ast_generator.py\n\n")
        f.write("from visitor import Visitor\n\n")
        f.write(f"class {base_name}:\n")
        f.write("    \"\"\"class for AST nodes.\"\"\"\n")
        f.write("    pass\n\n\n")

        # Each node class
        for t in types:
            class_name, fields = [part.strip() for part in t.split(":")]
            field_list = [f.strip() for f in fields.split(",")] if fields else []
            f.write(define_type(base_name, class_name, field_list))
            f.write("\n\n")


def define_type(base_name, class_name, fields):
    """
    Return the class source code string for `class_name`.
    """
    returnString = f"class {class_name}({base_name}):\n"
    args = ", ".join(fields)
    returnString += f"    def __init__(self, {args}):\n" if args else "    def __init__(self):\n"
    
    if not fields:
        returnString += "        pass\n"
    else:
        for field in fields:
            returnString += f"        self.{field} = {field}\n"

    returnString += "\n\n"

    returnString += "    def accept(self, visitor):\n"
    returnString += f"        return visitor.visit_{class_name}(self)\n"

    return returnString


if __name__ == "__main__":
    types = [
        "Binary     : left, operator, right",
        "Grouping   : expression",
        "Literal    : value",
        "Unary      : operator, right"
    ]
    define_ast("./src", "Expression", types)
    print("Wrote ./expression.py")
