# AUTO GENERATED BY: ast_generator.py

from statement import Statement

class Expression:
    """Base class for Expression AST nodes."""
    pass


class Assign(Expression):
    def __init__(self, name, value):
        self.name = name
        self.value = value

    def accept(self, visitor):
        return visitor.visit_AssignStmt(self)


class Binary(Expression):
    def __init__(self, left, operator, right):
        self.left = left
        self.operator = operator
        self.right = right


    def accept(self, visitor):
        return visitor.visit_Binary(self)


class Grouping(Expression):
    def __init__(self, expression):
        self.expression = expression


    def accept(self, visitor):
        return visitor.visit_Grouping(self)


class Literal(Expression):
    def __init__(self, value):
        self.value = value


    def accept(self, visitor):
        return visitor.visit_Literal(self)


class Unary(Expression):
    def __init__(self, operator, right):
        self.operator = operator
        self.right = right


    def accept(self, visitor):
        return visitor.visit_Unary(self)


class Variable(Expression):
    def __init__(self, name:str):
        self.name = name


    def accept(self, visitor):
        return visitor.visit_Variable(self)
    

class Call(Expression):
    def __init__(self, callee, paren, arguments):
        self.callee = callee
        self.paren = paren
        self.arguments = arguments

    def accept(self, visitor):
        return visitor.visit_Call(self)


