# AUTO GENERATED BY: ast_generator.py

from visitor import Visitor

class Expression:
    """class for AST nodes."""
    pass


class Binary(Expression):
    def __init__(self, left, operator, right):
        self.left = left
        self.operator = operator
        self.right = right


    def accept(self, visitor):
        return visitor.visit_Binary(self)


class Grouping(Expression):
    def __init__(self, expression):
        self.expression = expression


    def accept(self, visitor):
        return visitor.visit_Grouping(self)


class Literal(Expression):
    def __init__(self, value):
        self.value = value


    def accept(self, visitor):
        return visitor.visit_Literal(self)


class Unary(Expression):
    def __init__(self, operator, right):
        self.operator = operator
        self.right = right


    def accept(self, visitor):
        return visitor.visit_Unary(self)


