"""
Interpreter for Sloth
by Blake Collins
"""

from visitor import Visitor
from environment import Environment
from statement import *
from sloth_function import *


class Interpreter(Visitor):
    """Interprets and executes the Abstract Syntax Tree (AST) generated by the parser.
    
    Implements the visitor pattern to traverse AST nodes, evaluate expressions,
    and execute statements. Manages variable scopes and function calls.
    """
    
    def __init__(self):
        """Initialize global environment and native functions."""
        # Global scope that persists for the entire program execution
        self.globals = Environment()
        # Current scope (may be nested in function calls or blocks)
        self.environment = self.globals
        # Maps expressions to their scope distances for variable resolution
        self.locals = {}
        # Define built-in functions available to all programs
        self.globals.define("clock", ClockFunction())  # native clock()
        self.globals.define("delay", DelayFunction())  # native delay()

    def resolve(self, expr, dist):
        """Store the scope distance for a variable expression (used by resolver).
        
        Args:
            expr: The variable expression to track
            dist: The number of scope levels to traverse to find the variable
        """
        self.locals[expr] = dist

    def evaluate(self, expr):
        """Evaluate an expression node."""
        return expr.accept(self)
    

    def execute_block(self, statements, environment):
        """Execute a sequence of statements in a new scope.
        
        Args:
            statements: List of statement AST nodes to execute
            environment: The environment (scope) for these statements
        """
        # Save the current environment
        previous = self.environment
        try:
            # Switch to the new environment for this block
            self.environment = environment
            # Execute each statement in the block
            for stmt in statements:
                stmt.accept(self)
        finally:
            # Always restore the previous environment
            self.environment = previous


    def visit_Grouping(self, expr):
        """Evaluate a parenthesized expression."""
        return self.evaluate(expr.expression)


    def visit_Literal(self, expr):
        """Return a literal value."""
        return expr.value


    def visit_Unary(self, expr):
        """Evaluate a unary expression (-, !).
        
        Args:
            expr: Unary expression with operator and right operand
            
        Returns:
            The result of applying the operator to the operand
        """
        right = self.evaluate(expr.right)
        op = expr.operator.lexeme

        # Unary minus: negates a number
        if op == "-":
            if not isinstance(right, (int, float)):
                raise RuntimeError("Operand must be a number for unary '-'")
            return -right

        # Logical NOT: inverts truthiness
        if op == "!":
            return not right

        raise RuntimeError(f"Unknown unary operator {op}")

    def visit_Binary(self, expr):
        """Evaluate a binary expression with two operands.
        
        Handles arithmetic (+, -, *, /), comparison (>, >=, <, <=),
        and equality (==, !=) operations.
        
        Args:
            expr: Binary expression with left operator right operands
            
        Returns:
            Result of the operation (number, boolean, or string)
        """
        left = self.evaluate(expr.left)
        right = self.evaluate(expr.right)
        op = expr.operator.lexeme

        # Addition: supports both numeric and string concatenation
        if op == "+":
            if isinstance(left, str) or isinstance(right, str):
                return str(left) + str(right)
            if not isinstance(left, (int, float)) or not isinstance(right, (int, float)):
                raise RuntimeError("Operands must be numbers or strings for '+'")
            return left + right

        # Subtraction
        if op == "-":
            self._check_number_operands(op, left, right)
            return left - right

        # Multiplication
        if op == "*":
            self._check_number_operands(op, left, right)
            return left * right

        # Division
        if op == "/":
            self._check_number_operands(op, left, right)
            if right == 0:
                raise RuntimeError("Division by zero")
            return left / right

        # Equality operators
        if op == "==": return left == right
        if op == "!=": return left != right

        # Comparison operators
        if op in [">", ">=", "<", "<="]:
            self._check_number_operands(op, left, right)
            if op == ">": return left > right
            if op == ">=": return left >= right
            if op == "<": return left < right
            if op == "<=": return left <= right

        raise RuntimeError(f"Unknown binary operator {op}")

    def _check_number_operands(self, operator, left, right):
        """Ensure both operands are numeric."""
        if not isinstance(left, (int, float)) or not isinstance(right, (int, float)):
            raise RuntimeError(f"Operands must be numbers for '{operator}'")

    def visit_Variable(self, expr):
        """Look up a variable's value in the appropriate scope.
        
        Checks local scopes first (if variable distance is tracked),
        then falls back to the global scope.
        
        Args:
            expr: Variable expression containing the variable name
            
        Returns:
            The value stored in the variable
        """
        # Check if variable is in a local scope (resolved by the resolver)
        if expr in self.locals:
            distance = self.locals[expr]
            return self.environment.get_at(distance, expr.name)
        # Otherwise look it up in the global scope
        else:
            return self.globals.get(expr.name)

    # ============== STATEMENT VISITORS ==============

    def visit_AssignStmt(self, stmt):
        """Assign a value to an existing variable.
        
        Args:
            stmt: Assignment statement with variable name and value
            
        Returns:
            The assigned value
        """
        value = self.evaluate(stmt.value)

        # Check if variable is in a local scope
        if stmt in self.locals:
            distance = self.locals[stmt]
            self.environment.assign_at(distance, stmt.name, value)
        else:
            # Assign in global scope
            self.globals.assign(stmt.name, value)

        return value


    def visit_VarStmt(self, stmt):
        """Declare a variable with optional initializer."""
        self.environment.define(stmt.name, None)

        if stmt.initializer is not None:
            value = self.evaluate(stmt.initializer)
            self.environment.assign(stmt.name, value)
            
        value = self.evaluate(stmt.initializer) if stmt.initializer else None
        self.environment.define(stmt.name, value)

    def visit_IfStmt(self, stmt):
        """Evaluate an if/else statement.
        
        Args:
            stmt: If statement with condition, then branch, and optional else branch
        """
        # Execute then branch if condition is truthy
        if self._is_truthy(self.evaluate(stmt.condition)):
            stmt.then_branch.accept(self)
        # Execute else branch if it exists and condition is falsy
        elif stmt.else_branch:
            stmt.else_branch.accept(self)

    def _is_truthy(self, value):
        """Determine truthiness according to Sloth semantics.
        
        In Sloth, only None and False are falsy; everything else is truthy.
        
        Args:
            value: Value to evaluate for truthiness
            
        Returns:
            Boolean indicating whether the value is truthy
        """
        return not (value is None or value is False)

    def visit_WhileStmt(self, stmt):
        """Execute a while loop until condition becomes falsy.
        
        Args:
            stmt: While statement with condition and body
        """
        # Keep executing the body as long as condition is truthy
        while self._is_truthy(self.evaluate(stmt.condition)):
            stmt.body.accept(self)

    def visit_ForStmt(self, stmt):
        """Execute a for-loop using a scoped environment.
        
        Creates a new scope for the loop to isolate the loop variable.
        
        Args:
            stmt: For statement with initializer, condition, increment, and body
        """
        # Create a new scope for the loop
        previous = self.environment
        self.environment = Environment(previous)

        try:
            # Execute initializer (e.g., i = 0)
            if stmt.initializer:
                stmt.initializer.accept(self)

            # Loop until condition is false (or infinitely if no condition)
            while True if stmt.condition is None else self._is_truthy(self.evaluate(stmt.condition)):
                stmt.body.accept(self)
                # Execute increment after each iteration
                if stmt.increment:
                    stmt.increment.accept(self)
        finally:
            # Restore the previous environment when loop exits
            self.environment = previous

    def visit_PrintStmt(self, stmt):
        """Print a value using Sloth's formatting rules.
        
        Formats booleans as TRUE/FALSE and None as NULL.
        
        Args:
            stmt: Print statement with expression to print
        """
        value = self.evaluate(stmt.expression)

        # Format output according to Sloth semantics
        if value is True: print("TRUE")
        elif value is False: print("FALSE")
        elif value is None: print("NULL")
        else: print(value)

    def visit_ExpressionStmt(self, stmt):
        """Evaluate an expression statement."""
        self.evaluate(stmt.expression)

    def visit_Block(self, stmt):
        """Execute a block with a new scoped environment.
        
        Creates a new local scope for variables declared in the block.
        
        Args:
            stmt: Block statement containing multiple statements
        """
        # Create a new environment with the current one as parent
        previous = self.environment
        self.environment = Environment(previous)

        try:
            # Execute all statements in the block
            for statement in stmt.statements:
                statement.accept(self)
        finally:
            # Restore the previous environment
            self.environment = previous

    def visit_Function(self, stmt):
        """Define a new function in the current environment.
        
        Creates a SlothFunction object that captures the current environment
        for closure support.
        
        Args:
            stmt: Function statement with name and body
        """
        # Create function object with closure (captured environment)
        function = SlothFunction(stmt, self.environment)
        # Store function in the current environment
        self.environment.define(stmt.name, function)

    def visit_ReturnStmt(self, stmt):
        """Evaluate a return statement.
        
        Raises a ReturnException to unwind the call stack and exit the function.
        
        Args:
            stmt: Return statement with optional return value
        """
        # Evaluate the return value (None if not specified)
        value = self.evaluate(stmt.value) if stmt.value else None
        # Throw exception to exit the function
        raise ReturnException(value)

    def visit_Call(self, expr):
        """Handle function calls.
        
        Evaluates the callee and arguments, then invokes the function.
        
        Args:
            expr: Call expression with callee and arguments
            
        Returns:
            The return value from the function
        """
        # Get the function object
        callee = self.evaluate(expr.callee)
        # Evaluate all arguments
        arguments = [self.evaluate(arg) for arg in expr.arguments]

        # Ensure callee is callable
        if not isinstance(callee, SlothCallable):
            raise RuntimeError(f"[Line {expr.paren.line}] Only functions can be called.")

        # Check argument count
        if len(arguments) != callee.arity():
            raise RuntimeError(f"[Line {expr.paren.line}] Expected {callee.arity()} arguments but got {len(arguments)}.")

        # Call the function
        return callee.call(self, arguments)
    

