# AUTO GENERATED BY: ast_generator.py


class Statement:
    """Base class for Statement AST nodes."""
    pass


class ExpressionStmt(Statement):
    def __init__(self, expression):
        self.expression = expression


    def accept(self, visitor):
        return visitor.visit_ExpressionStmt(self)


class PrintStmt(Statement):
    def __init__(self, expression):
        self.expression = expression


    def accept(self, visitor):
        return visitor.visit_PrintStmt(self)
 
    
class AssignStmt(Statement):
    def __init__(self, name, value):
        self.name = name
        self.value = value

    def accept(self, visitor):
        return visitor.visit_AssignStmt(self)


class VarStmt(Statement):
    def __init__(self, name, initializer):
        self.name = name
        self.initializer = initializer


    def accept(self, visitor):
        return visitor.visit_VarStmt(self)
    

class IfStmt(Statement):
    def __init__(self, condition, then_branch, else_branch):
        self.condition = condition
        self.then_branch = then_branch
        self.else_branch = else_branch

    def accept(self, visitor):
        return visitor.visit_IfStmt(self)


class WhileStmt(Statement):
    def __init__(self, condition, body):
        self.condition = condition
        self.body = body

    def accept(self, visitor):
        return visitor.visit_WhileStmt(self)
    
    
class ForStmt(Statement):
    def __init__(self, initializer, condition, increment, body):
        self.initializer = initializer    # VarStmt | ExpressionStmt | None
        self.condition = condition        # Expression | None
        self.increment = increment        # Expression | None
        self.body = body                  # Block

    def accept(self, visitor):
        return visitor.visit_ForStmt(self)


class Block(Statement):
    def __init__(self, statements):
        self.statements = statements


    def accept(self, visitor):
        return visitor.visit_Block(self)
    

class Function(Statement):
    def __init__(self, name, params, body):
        self.name = name
        self.params = params
        self.body = body

    def accept(self, visitor):
        return visitor.visit_Function(self)
    

class ReturnStmt(Statement):
    def __init__(self, keyword, value):
        self.keyword = keyword
        self.value = value

    def accept(self, visitor):
        return visitor.visit_ReturnStmt(self)

