# AUTO GENERATED BY: ast_generator.py

from visitor import Visitor

class Statement:
    """Base class for Statement AST nodes."""
    pass


class ExpressionStmt(Statement):
    def __init__(self, expression):
        self.expression = expression


    def accept(self, visitor):
        return visitor.visit_ExpressionStmt(self)


class PrintStmt(Statement):
    def __init__(self, expression):
        self.expression = expression


    def accept(self, visitor):
        return visitor.visit_PrintStmt(self)
 
    
class AssignStmt:
    def __init__(self, name, value):
        self.name = name
        self.value = value

    def accept(self, visitor):
        return visitor.visit_AssignStmt(self)


class VarStmt(Statement):
    def __init__(self, name, initializer):
        self.name = name
        self.initializer = initializer


    def accept(self, visitor):
        return visitor.visit_VarStmt(self)


class Block(Statement):
    def __init__(self, statements):
        self.statements = statements


    def accept(self, visitor):
        return visitor.visit_Block(self)


